pass-culture/pass-culture-institutional

tsconfig.json

https://passculture.atlassian.net/browse/PC-25058

(PC-25058) Update tsconfig

---

.github/PULL_REQUEST_TEMPLATE.md

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25056
I have:

(PC-25056) feat(github): Add template PR

---

.github/workflows/dev_on_push_workflow_main.yml
frontend/.eslintrc.js
frontend/package.json
frontend/src/pages/__snapshots__/home.test.tsx.snap
frontend/src/pages/home.test.tsx
frontend/src/pages/index.tsx

Pour la CI : voir la doc de GitHub <https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet>

(BSR) chore(eslint): improve eslint rules

---

backend/config/database.ts
backend/src/admin/tsconfig.json
frontend/src/pages/about.tsx
frontend/src/utils/fetchAPI.ts

(BSR) feat(sonar): fix sonar issues

---

package.json

(BSR) feat(yarn): Add yarn audit:all in ./package.json

---

frontend/package.json
frontend/yarn.lock

(BSR) feat(tests): Add Vitest coverage

---

LICENSE

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25056
I have:

(PC-25056) feat(github): Create LICENSE

---

.github/workflows/dev_on_pull_request_deadcode.yml
.gitignore
README.md
backend/.ts-prunerc
backend/README.md
backend/package.json
backend/yarn.lock
frontend/.ts-prunerc
frontend/README.md
package.json
scripts/check_dead_code.sh
scripts/check_dead_code_introduced.sh
scripts/dead_code_snapshot.txt

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25362
I have:

(PC-25362) feat(tests): Add ts-prune check in CI 

---

.github/workflows/dev_on_pull_request_sonar.yml
README.md
frontend/vitest.config.ts
sonar-project.properties

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25430
I have:
No Coverage information sur cette PR parce que pas aucun code ajouté. J'ai fait un test en ajoutant du code non testé et ça met bien 0% de coverage sur les nouvelles lignes.

(PC-25430) feat(sonar): Get code coverage

---

sonar-project.properties

(BSR) feat(Sonar): Update sonar config

---

schema.md

(BSR) docs(update): added doc schema

---

README.md
backend/README.md

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25315

(PC-25315) docs(update): improve readme

---

frontend/public/.well-known/security.txt

~~Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX~~ Email

(BSR) chore(security): add security txt file

---

.github/workflows/dev_on_pull_request_title_checker.yml
README.md

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25053

test: change test for PR titles to follow 'conventional commits'

---

.github/workflows/dev_on_pr_build_docker.yml
.github/workflows/reusable_docker_build.yml
.gitignore
content_management_system/.dockerignore
content_management_system/Dockerfile
docker-compose.yaml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25924

build(docker): creation image docker (PC-25924) 

---

content_management_system/config/plugins.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26040

build: add configuration for deployment plugin (PC-26040)

---

.github/dependabot.yml

fix: Remove unused prefix

---

.github/workflows/on_dispatch_deploy_staging.yml
.github/workflows/on_push_or_dispatch_deploy_testing.yml
.github/workflows/reusable_cms_deploy.yml
.github/workflows/reusable_docker_build.yml
.github/workflows/reusable_public_site_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26090
I have:

ci: add strapi deployment for testing

---

.github/workflows/reusable_public_site_deploy.yml

Ajout de la valeur ID_TOKEN qui permet de se connecter au strapi à travers IAP.

ci: add ID_TOKEN variable from GCP secret manager

---

.github/dependabot.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26747
I have:

feat(dependabot): add github-actions check for Dependabot

---

public_website/__tests__/fetchAPI.test.ts
public_website/src/utils/fetchAPI.ts

Co-authored-by: bruno ebstein <bruno.ebstein@passculture.app>

fix: Allowed build locally and adapted tests

---

.github/workflows/reusable_public_site_deploy.yml
.gitignore
public_website/.firebaserc
public_website/firebase.json

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26859
I have:

ci: setup firebase deploy (PC-26859)

---

.vscode/settings.json
README.md
content_management_system/README.md
public_website/README.md

- settings.json is updated for recent change in eslint

docs: update information about Node, Docker, Local Build

---

.github/dependabot.yml

chore(dependabot): Add ignore udpate-types patch in depdandabot config

---

content_management_system/src/api/health/routes/health.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27799

feat: strapi health endpoint

---

content_management_system/src/index.ts
public_website/src/utils/fetchBackend.ts

fix: remove content type on fetchBackend

---

.github/workflows/on_dispatch_deploy_staging.yml
.github/workflows/on_push_or_dispatch_deploy_testing.yml
.github/workflows/reusable_public_site_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27767
I have:

ci: add backend url to build step (PC-27767)

---

.github/workflows/reusable_cms_deploy.yml
.github/workflows/reusable_public_site_deploy.yml

ci: add slack notifications on ci dployment

---

sonar-project.properties

feat: ignore 2 Sonar rules

---

public_website/__tests__/components/header.test.tsx
sonar-project.properties

feat: update coverage exclusions

---

sonar-project.properties

chore: update sonar coverage exclusions

---

.github/workflows/on_dispatch_deploy_production.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28021
I have:

ci: add production environment (PC-28021)

---

public_website/src/pages/_app.tsx
public_website/src/ui/components/footer/Footer.tsx
public_website/src/ui/components/skipLink/SkipLink.tsx

feat: add skip links

---

content_management_system/src/components/home/hero-section.json
content_management_system/types/generated/components.d.ts
public_website/public/images/home-circles-mobile.svg
public_website/src/pages/index.tsx
public_website/src/theme/theme.ts
public_website/src/types/components.d.ts
public_website/src/ui/components/home/Eligibility.tsx
public_website/src/ui/components/home/Hero.tsx

feat: add hero background

---

content_management_system/config/middlewares.ts
content_management_system/config/plugins.ts
content_management_system/package.json
content_management_system/yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28297
I have:

feat: add s3 upload provider to strapi (PC-28297)

---

public_website/src/ui/components/button/Button.tsx
public_website/src/ui/globalstyles.tsx

feat: add focus styles

---

content_management_system/config/plugins.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28515
I have:

fix: let gcs plugin know that files are publicly available

---

public_website/.eslintrc.js
public_website/src/lib/blocks/SimplePushCta.tsx
public_website/src/lib/blocks/SocialMedia.tsx
public_website/src/pages/aide.tsx
public_website/src/ui/components/help/Faq.tsx
public_website/src/ui/components/help/Hero.tsx
public_website/src/utils/fetchCMS.ts
public_website/yarn.lock

PR pour les retours non pris dans cette PR : https://github.com/pass-culture/pass-culture-institutional/pull/207
I have:

fix: Bsr fix help page

---

.github/workflows/on_push_or_dispatch_deploy_testing.yml

ci: switch cluster for testing deployment

---

.github/workflows/reusable_public_site_deploy.yml
content_management_system/README.md
public_website/.env.production
public_website/README.md
public_website/__tests__/pages/index.test.tsx
public_website/__tests__/pages/liste-jeune.test.tsx
public_website/__tests__/pages/simulateur.test.tsx
public_website/__tests__/utils/fetchBackend.test.ts
public_website/__tests__/utils/fetchCMS.test.ts
public_website/src/utils/apiHelpers.ts
public_website/src/utils/fetchBackend.ts

fix: Added NEXT_PUBLIC_ to env variables

---

.github/workflows/on_dispatch_deploy_production.yml
.github/workflows/on_dispatch_deploy_staging.yml
.github/workflows/on_dispatch_full_deploy_production.yml
.github/workflows/on_dispatch_full_deploy_staging.yml
.github/workflows/on_push_or_dispatch_deploy_testing.yml
.github/workflows/on_push_or_dispatch_full_deploy_testing.yml
.github/workflows/reusable_cms_deploy.yml
.github/workflows/reusable_public_site_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28859
I have:

ci: only deploy public site when strapi button is used (PC-28859)

---

public_website/src/pages/[...slug].tsx

Corrige un bug empêchant le déploiement du front

fix: add populated properties to generic page api call

---

public_website/.firebaserc
public_website/firebase.json

ci: setup firebase production environment

---

.github/workflows/on_push_or_dispatch_deploy_testing.yml
.github/workflows/on_push_or_dispatch_full_deploy_testing.yml
public_website/.env.production
public_website/README.md

feat(playlist): use production API url instead testing

---

.github/workflows/on_dispatch_deploy_staging.yml
.github/workflows/on_dispatch_full_deploy_staging.yml

chore(ci): use prod backend url for staging workflows

---

public_website/src/lib/blocks/Faq.tsx
public_website/src/lib/blocks/SimplePushCta.tsx
public_website/src/pages/aide-enseignants.tsx

feat: fix help mobile

---

public_website/src/ui/components/button/Button.tsx

feat: fix button color

---

content_management_system/.strapi/client/app.js
content_management_system/package.json
content_management_system/src/api/event/content-types/event/schema.json
content_management_system/src/api/news/content-types/news/schema.json
content_management_system/src/api/resource/content-types/resource/schema.json
content_management_system/types/generated/contentTypes.d.ts
content_management_system/yarn.lock
public_website/src/pages/actualites-jeunes-parents.tsx
public_website/src/pages/actualites-pass-culture.tsx
public_website/src/pages/actualites-rdv-acteurs-culturels.tsx
public_website/src/pages/etudes-pass-culture.tsx
public_website/src/pages/presse.tsx
public_website/src/pages/ressources-enseignants.tsx
public_website/src/pages/ressources-pass-culture.tsx
public_website/src/types/components.d.ts
public_website/src/types/contentTypes.d.ts

feat: added multiple select field

---

.github/workflows/dev_on_push_workflow_main.yml
docker-compose.yaml
public_website/.gitignore
public_website/Dockerfile

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29091
I have:

ci: create docker image for next preview (PC-29091)

---

public_website/src/lib/blocks/FilterContainer.tsx
public_website/src/ui/components/header/mobile/MobileMenu.tsx

feat: fix button colors

---

content_management_system/src/api/liste-offre/content-types/liste-offre/schema.json
content_management_system/types/generated/contentTypes.d.ts
public_website/src/types/contentTypes.d.ts
public_website/src/ui/components/offer-section/OfferSection.tsx

feat: fix offers page

---

content_management_system/src/components/common/link.json
content_management_system/src/components/header/account-item.json
content_management_system/src/components/header/login-items.json
content_management_system/types/generated/components.d.ts
public_website/__tests__/fixtures/home.ts
public_website/__tests__/pages/index.test.tsx
public_website/src/lib/analytics/analyticsProvider.ts
public_website/src/lib/analytics/helpers.ts
public_website/src/lib/blocks/DoublePushCta.tsx
public_website/src/lib/blocks/PushCTA.tsx
public_website/src/ui/components/buttonWithCTA/ButtonWithCTA.tsx
public_website/src/ui/components/footer/Footer.tsx
public_website/src/ui/components/header/AccountItem.tsx
public_website/src/ui/components/header/MegaMenu.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29268
Question: when navigating directly to a page like http://localhost:3000/comment-debloquer-ton-credit, is tracking instantiated? (tracking is started in index)
Test tracking on Button component:
Test tracking on AppBanner component:
Test tracking on AccountItem component:
Test tracking on Link component:
Result on Firebase:

feat: analytics (PC-29268)

---

.github/workflows/reusable_public_site_deploy.yml
public_website/.gitignore
public_website/next.config.js
public_website/package.json
public_website/sentry.client.config.ts
public_website/sentry.edge.config.ts
public_website/sentry.server.config.ts
public_website/src/pages/_error.tsx
public_website/yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27511
I have:

feat(sentry): add sentry (PC-27511)

---

public_website/src/lib/analytics/analyticsProvider.ts
public_website/src/lib/analytics/helpers.ts
public_website/src/pages/_app.tsx
public_website/src/pages/index.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29278
I have:

feat: add page view analytics

---

README.md
public_website/.eslintrc.js
public_website/src/lib/blocks/Image.tsx
public_website/src/lib/blocks/ImageGallery.tsx
public_website/src/pages/404.tsx
public_website/src/pages/index.tsx
public_website/src/types/components.d.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28836

refactor: code review (PC-28836)

---

.github/dependabot.yml

feat(Dependabot): remove reviewers from dependabot.yml

---

.github/workflows/on_push_or_dispatch_deploy_testing.yml
.github/workflows/on_push_or_dispatch_full_deploy_testing.yml
docker-compose.yaml

PR so that testing is iso to production for offer playlists

fix: use prod backend in testing

---

.github/workflows/dev_on_push_workflow_main.yml

ci: add image signing

---

public_website/src/lib/blocks/verticalCarousel/NavigationWithArrow.tsx
public_website/src/lib/blocks/verticalCarousel/NavigationWithDots.tsx
public_website/src/lib/blocks/verticalCarousel/VerticalCarousel.tsx
public_website/src/pages/index.tsx
public_website/src/utils/carouselHelper.ts

Cette PR permet de mieux gérer l'état de navigation du composant VerticalCarousel.
J'en ai profité pour extraire la partie navigation du carousel qui pourra être partagé avec les autres types de carrousels selon la situation.

fix: navigation verticalCarousel

---

public_website/src/lib/blocks/FilterContainer.tsx
public_website/src/theme/style.ts
public_website/src/ui/components/simulator/SliderField.tsx

Cette PR permet de mettre à jour l'UI de la boite selection de l'âge qui ne s'affiche que en mobile.
Quelques optimisations de code sur cette partie ont été faites.

fix: mise à jour ui select pour le simulateur

---

public_website/src/lib/blocks/PiledCards/PiledCards.tsx
public_website/src/lib/blocks/experienceVideoCarousel/experienceVideoCarousel.tsx
public_website/src/pages/liste-offres.tsx
public_website/src/ui/components/OutlinedText.tsx
public_website/src/ui/components/nav-carousel/NavigationWithArrow.tsx
public_website/src/ui/components/offer-section/OfferSection.tsx
public_website/src/ui/components/simulator/Simulator.tsx
public_website/src/ui/components/simulator/SliderField.tsx

Cette PR fixe quelques retours UI/UX suite à la vérification des corrections des tickets.

fix: ui & ux

---

public_website/src/lib/blocks/offersCarousel/offersCarousel.tsx
public_website/src/ui/globalstyles.tsx

Cette PR permet de faire un test de fluidité sur le carrousel des offres sur mobile.

fix: props carrousel offre

---

public_website/src/lib/blocks/SimpleTextV2.tsx

Cette PR permet de mieux gérer taille/placement des images ajoutés depuis d'éditeur enrichi du composant SimpleText.

fix: dimensions img article

---

public_website/src/lib/blocks/PiledCards/PiledCards.tsx
public_website/src/lib/blocks/PiledCards/PiledCardsCarouselSlide.tsx
public_website/src/utils/apiHelpers.ts

Suite à la demande de la prise en charge des br dans le bloc description des slides empilées, j'ai ajouté le parseText sur celui-ci.

fix: ajout du parseText sur la description

---

public_website/src/lib/blocks/CenteredText.tsx
public_website/src/lib/blocks/DoublePushCta.tsx
public_website/src/lib/blocks/Header.tsx
public_website/src/lib/blocks/ImageText.tsx
public_website/src/lib/blocks/PiledCards/PiledCards.tsx
public_website/src/lib/blocks/experienceVideoCarousel/experienceVideoCarousel.tsx
public_website/src/lib/blocks/experienceVideoCarousel/experieneVideoCarouselSlide.tsx
public_website/src/lib/blocks/offersCarousel/offersCarouselSlide.tsx
public_website/src/lib/blocks/verticalCarousel/VerticalCarousel.tsx
public_website/src/pages/[...slug].tsx
public_website/src/pages/liste-offres.tsx
public_website/src/theme/fonts.ts
public_website/src/theme/theme.ts
public_website/src/ui/components/breadcrumb/Breadcrumb.tsx
public_website/src/ui/components/header/AccountDropdown.tsx
public_website/src/ui/components/header/Header.tsx
public_website/src/ui/components/header/MegaMenu.tsx
public_website/src/ui/components/offer-section/OfferSection.tsx

Cette PR permet de faire ajuste sur le bloc liste des offres. 
D'autres corrections UI/UX ont été réalisées et un bug sur le scroll des cartes empilées a été corrigé.

fix: offres et autres

---

public_website/src/ui/components/header/Header.tsx
public_website/src/ui/components/header/MegaMenu.tsx

Ajout d'un bouton fermer sur le megamenu et meilleure gestion du background du header selon les pages.

feat: ajout bouton fermer megamenu

---

public_website/src/lib/blocks/DoublePushCta.tsx
public_website/src/lib/blocks/Separator.tsx
public_website/src/lib/blocks/SimplePushCta.tsx

Cette PR met à jour les styles des push cta.

fix: bloc push cta

---

public_website/src/lib/blocks/Header.tsx
public_website/src/lib/blocks/PiledCards/PiledCards.tsx
public_website/src/lib/blocks/PushCTA.tsx
public_website/src/lib/blocks/SimplePushCta.tsx
public_website/src/lib/blocks/experienceVideoCarousel/experienceVideoCarousel.tsx
public_website/src/lib/blocks/experienceVideoCarousel/experieneVideoCarouselSlide.tsx
public_website/src/lib/blocks/keyNumberCarousel/keyNumberCarouselSlide.tsx
public_website/src/lib/blocks/offersCarousel/offersCarouselSlide.tsx
public_website/src/lib/blocks/verticalCarousel/VerticalCarousel.tsx
public_website/src/pages/index.tsx
public_website/src/pages/liste-offres.tsx
public_website/src/ui/components/home/Recommendations.tsx

Encore quelques corrections de design proposées.

fix: design

---

public_website/src/lib/blocks/DoublePushCta.tsx
public_website/src/lib/blocks/LittleList.tsx
public_website/src/lib/blocks/PushCTA.tsx
public_website/src/lib/blocks/SimplePushCta.tsx
public_website/src/lib/blocks/verticalCarousel/VerticalCarousel.tsx
public_website/src/theme/style.ts
public_website/src/ui/components/footer/Footer.tsx

Cette PR corrige les regressions de la précédente PR et traite une nouvelle demande concernant l'affichage d'une flèche dans les simplelist.

fix: design regression

---

public_website/src/lib/blocks/experienceVideoCarousel/experienceVideoCarousel.tsx
public_website/src/lib/blocks/verticalCarousel/VerticalCarousel.tsx
public_website/src/pages/liste-offres.tsx

Fix un padding sur un caroussel.

fix: padding slider

---

content_management_system/package.json
content_management_system/yarn.lock

Add https://market.strapi.io/plugins/strapi-plugin-sitemap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31650
I have:
- [-] Made sure my feature is **working on different browsers** (Chrome, Firefox, Safari). **No it's just a plugin for the BO**

chore: add sitemap plugin to be installed

---

public_website/src/lib/blocks/SimpleTextV2.tsx
public_website/src/types/contentTypes.d.ts
public_website/src/ui/components/offer-section/OfferSection.tsx

feat: add missing styles to SimpleText block

---

content_management_system/.strapi/client/app.js
content_management_system/package.json
content_management_system/types/generated/components.d.ts
content_management_system/types/generated/contentTypes.d.ts
public_website/public/robots.txt
public_website/public/sitemap.xml
public_website/src/types/components.d.ts
public_website/src/types/contentTypes.d.ts

feat: remove old sitemap and use plugin

---

content_management_system/config/middlewares.ts
content_management_system/config/server.ts

feat: add public acces to sitemap url

---

public_website/src/domain/pages/pages.actions.ts
public_website/src/pages/[...slug].tsx
public_website/src/pages/actualites-pass-culture.tsx
public_website/src/pages/etudes-pass-culture.tsx
public_website/src/pages/evenement/[slug].tsx
public_website/src/pages/presse.tsx
public_website/src/pages/ressources-enseignants.tsx
public_website/src/pages/ressources-pass-culture.tsx
public_website/src/pages/ressources/[slug].tsx

feat: try to fix redirect from presse section

---

public_website/src/pages/ressources-pass-culture.tsx

feat: Fix deploy

---

content_management_system/src/api/event/content-types/event/schema.json
content_management_system/src/api/news/content-types/news/schema.json
content_management_system/src/api/page/content-types/page/schema.json
content_management_system/src/api/resource/content-types/resource/schema.json
content_management_system/src/components/block/simple-text-v2.json
content_management_system/types/generated/components.d.ts
content_management_system/types/generated/contentTypes.d.ts
public_website/src/types/components.d.ts
public_website/src/types/contentTypes.d.ts

feat: Update simple text type and collection type display name

---

public_website/src/lib/blocks/EventListItems.tsx
public_website/src/lib/blocks/ListItems.tsx
public_website/src/lib/blocks/ResourceItems.tsx

feat: add cursor pointer

---

public_website/src/ui/components/header/MegaMenu.tsx

feat: fix overlay with scroll

---

public_website/src/pages/actualites-jeunes-parents.tsx
public_website/src/pages/actualites-pass-culture.tsx
public_website/src/pages/actualites-rdv-acteurs-culturels.tsx
public_website/src/pages/etudes-pass-culture.tsx
public_website/src/pages/presse.tsx
public_website/src/pages/ressources-pass-culture.tsx

https://sentry.passculture.team/organizations/sentry/issues/1611095/?project=12&referrer=project-issue-stream

fix: failed to fetch (made fetchData and fetchEventData conditional)

---

public_website/public/sitemap.xml

feat: udpate sitemap

---

public_website/src/utils/fetchCMS.ts

feat: try to fix preview mode

---

public_website/.firebaserc
public_website/firebase.json

feat: change redirection for app urls

---

content_management_system/src/components/header/mega-menu.json
content_management_system/types/generated/components.d.ts
public_website/src/types/components.d.ts

feat(menu): update mega menu types

---

public_website/src/pages/_document.tsx

feat(html): add default body background color

---

public_website/src/ui/components/skipLink/SkipLink.tsx

I have:
| Desktop - Chrome  |               |   ![Capture d’écran 2024-10-04 à 14 45 45](https://github.com/user-attachments/assets/702a4c7a-9dbe-42d0-b694-0328977b934f) ![Capture d’écran 2024-10-04 à 14 45 37](https://github.com/user-attachments/assets/6a25aebc-9d87-4ab8-9ffb-178e473b255a)   |

feat(menu): fix skip link

---

public_website/src/pages/index.tsx

I have:
| Desktop - Chrome - Zoom 200%  |   ![Capture d’écran 2024-10-04 à 17 10 26](https://github.com/user-attachments/assets/f9645065-39f2-4ce8-a417-5692e9c040ae)  |    ![Capture d’écran 2024-10-04 à 17 01 12](https://github.com/user-attachments/assets/ca161beb-ce9a-4d07-8341-d01f87d6dc9c) |
| Desktop - Chrome - normal |               |  ![Capture d’écran 2024-10-04 à 17 00 38](https://github.com/user-attachments/assets/388694a5-3520-49c9-a036-0dc76d6711f1)     |
| Tablet - Chrome    |               |  ![Capture d’écran 2024-10-04 à 17 00 31](https://github.com/user-attachments/assets/0902b847-dffb-46fa-9de7-041586 …

feat(home): remove overflow hidden on desktop home

---

public_website/public/sitemap.xml

feat(seo): remove page that should not appear on google search

---

public_website/src/ui/components/header/MegaMenu.tsx

feat(menu): add quit menu with escape button

---

public_website/src/hooks/useConsent.ts
public_website/src/pages/_app.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32327

refactor(firebase): analytics

---

.github/workflows/dev_on_pull_request_deadcode.yml
.github/workflows/dev_on_pull_request_sonar.yml
.github/workflows/dev_on_pull_request_title_checker.yml
.github/workflows/dev_on_push_workflow_main.yml
.github/workflows/reusable_cms_deploy.yml
.github/workflows/reusable_public_site_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32361

(PC-32361) Change image used by ci

---

.github/workflows/on_dispatch_deploy_production.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33028

(PC-33028) fix github action permission

---

.github/workflows/on_push_or_dispatch_full_deploy_testing.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33586

ci: Add permission to workflow

---

content_management_system/types/generated/components.d.ts
public_website/__tests__/utils/filterNonEmptyLabel.test.ts
public_website/src/domain/pages/pages.path.ts
public_website/src/pages/plan-du-site.tsx
public_website/src/ui/components/sitemap/MenuSection.tsx
public_website/src/ui/components/sitemap/SitemapLinkItem.tsx
public_website/src/utils/filterNonEmptyLabel.ts

Cette PR permet d'ajouter une nouvelle page au site : le plan du site.
Le plan du site d'affiche sous forme de blocs et de listes selon l'organisation du header et du footer.

feat: add sitemap page

---

public_website/sentry.client.config.ts

Ajustement des taux d'échantillonnage Sentry pour optimiser les performances et les coûts tout en maintenant une surveillance efficace.
- `tracesSampleRate` : 100% → 10%
- `replaysSessionSampleRate` : 100% → 0%
- `replaysOnErrorSampleRate` : 100% → 10%
- Réduction de la consommation de ressources
- Optimisation des coûts Sentry
- Amélioration des performances du site
- Conservation d'un niveau de monitoring pertinent pour le debugging

perf(monitoring): reduce sentry sampling rates to optimize costs

---

.github/workflows/on_dispatch_deploy_production.yml
.github/workflows/on_dispatch_full_deploy_production.yml
.github/workflows/on_push_or_dispatch_deploy_testing.yml
.github/workflows/on_push_or_dispatch_full_deploy_testing.yml
.github/workflows/reusable_cms_deploy.yml
.github/workflows/reusable_public_site_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32934
I have:

PC-32934 - tinyproxy for site instit CIs

---

.github/workflows/on_dispatch_deploy_production.yml

Fix typo in CI

---

.github/workflows/reusable_cms_deploy.yml
.github/workflows/reusable_public_site_deploy.yml

Fix secrets for CI

---

public_website/firebase.json

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33942
cf https://firebase.google.com/docs/hosting/full-config?hl=fr

(PC-33942) Remove trailling slash at the end

---

content_management_system/Dockerfile

fix(sitemap): fix issue with docker run

---

.github/workflows/on_push_or_dispatch_deploy_testing.yml

fix(workflow): fix testing deployment

---

.github/workflows/on_dispatch_full_deploy_production.yml

Devrait fix cette erreur : https://github.com/pass-culture/pass-culture-institutional/actions/runs/13372586194

(BSR)(ci): fix typo in deploy production workflow

---

.github/workflows/on_dispatch_full_deploy_production.yml

fix(workflow): fix production deployment

---

content_management_system/types/generated/components.d.ts
public_website/package.json
public_website/src/hooks/useAxeptio.ts
public_website/src/hooks/useConsent.ts
public_website/src/hooks/useGoogleAnalytics.ts
public_website/src/hooks/useOnClickAnalytics.ts
public_website/src/lib/analytics/analyticsProvider.ts
public_website/src/lib/analytics/config.ts
public_website/src/pages/_app.tsx
public_website/src/pages/_document.tsx
public_website/yarn.lock

Cette PR apporte plusieurs modifications liées au suivi analytique et à la gestion du consentement utilisateur. Les principaux changements sont :
- **Suppression de Firebase Analytics** : Retrait de la dépendance `firebase` ainsi que des appels liés à Firebase Analytics.
- **Ajout de Google Analytics via gtag.js** : Mise en place d'un nouveau système de tracking basé sur `gtag.js`.
- **Mise à jour du système de consentement (Axeptio)** :
- Ajout d'un event listener sur la complétion du consentement (`cookies:complete`).
- Ajout d'un dispatch d'événement `axeptioConsentAccepted` pour notifier les autres scripts de la mise à jour du consentement.
- Gestion du tracking Google Analytics en fonction du consentement utilisateur.
- **Ajout de la vérification Google Search Console** : Inclusion …

feat(analytics): remove firebase and add google analytics

---

public_website/firebase.json

fix(firebase): remove trailing slash for prod

---

content_management_system/types/generated/components.d.ts
public_website/__tests__/pages/simulateur.test.tsx
public_website/src/pages/simulateur.tsx

This reverts commit 5ff228de7e61161a329e3d6f8d6002bfc0948890.
I have:

Revert "fix(simulator): hide simulator (#560)"

---

content_management_system/types/generated/components.d.ts
public_website/src/lib/blocks/LatestNews.tsx
public_website/src/pages/actualite/[slug].tsx
public_website/src/pages/aide-enseignants.tsx
public_website/src/pages/blog-tech/[slug].tsx
public_website/src/pages/index.tsx
public_website/src/pages/ressources/[slug].tsx
public_website/src/types/props.ts

fix(blogtech): issue with blog tech link

---

content_management_system/types/generated/components.d.ts
public_website/package.json
public_website/yarn.lock

next : 14.2.8 → 15.2.4
Next.js 15 introduit plusieurs changements et potentielles breaking changes.
Bien consulter le changelog officiel : https://nextjs.org/docs/upgrading
Pensez à surveiller les comportements runtime spécifiques (middleware, app router, etc.)
Certaines features ou warnings peuvent apparaître avec la v15 (ex: turbotrace, app directory refinements...)

feat(nextjs): upgrade nextjs version

---

.github/workflows/reusable_cms_deploy.yml
.github/workflows/reusable_public_site_deploy.yml

ci(deploy): allow cloning pc-firestore-cli (BSR) 

---

content_management_system/src/api/actualites-pass-culture/content-types/actualites-pass-culture/schema.json
content_management_system/src/api/actualites-rdv-acteurs-culturel/content-types/actualites-rdv-acteurs-culturel/schema.json
content_management_system/src/api/blogtech-pass-culture/content-types/blogtech-pass-culture/schema.json
content_management_system/src/api/blogtech/content-types/blogtech/schema.json
content_management_system/src/api/etudes-pass-culture/content-types/etudes-pass-culture/schema.json
content_management_system/src/api/event/content-types/event/schema.json
content_management_system/src/api/help-cultural-actors/content-types/help-cultural-actors/schema.json
content_management_system/src/api/help-teachers/content-types/help-teachers/schema.json
content_management_system/src/api/help/content-types/help/schema.json
content_management_system/src/api/home/content-types/home/schema.json
content_management_system/src/api/liste-jeune/content-types/liste-jeune/schema.json
content_management_system/src/api/liste-offre/content-types/liste-offre/schema.json
content_management_system/src/api/news/content-types/news/schema.json
content_management_system/src/api/not-found/content-types/not-found/schema.json
content_management_system/src/api/page/content-types/page/schema.json
content_management_system/src/api/presse/content-types/presse/schema.json
content_management_system/src/api/reglement/content-types/reglement/schema.json
content_management_system/src/api/reglements-pass-culture/content-types/reglements-pass-culture/schema.json
content_management_system/src/api/resource/content-types/resource/schema.json
content_management_system/src/api/ressources-pass-culture/content-types/ressources-pass-culture/schema.json
content_management_system/src/api/rubrique-instit-pass-culture/content-types/rubrique-instit-pass-culture/schema.json
content_management_system/src/api/rubrique-instit/content-types/rubrique-instit/schema.json
content_management_system/src/api/simulator/content-types/simulator/schema.json
content_management_system/types/generated/components.d.ts
content_management_system/types/generated/contentTypes.d.ts
public_website/src/types/components.d.ts
public_website/src/types/contentTypes.d.ts

feat(seo): make seo required

---

.github/workflows/reusable_cms_deploy.yml

https://www.notion.so/passcultureapp/M-J-binaire-Helmfile-207ad4e0ff98808fa82cca26f99bd159?source=copy_link
À ne pas merger avant https://github.com/pass-culture/common-workflows/pull/45

ci(deploy): use new render-push-manifest for helmfile v1 (IC-235)

---

.github/workflows/reusable_cms_deploy.yml

Link to JIRA ticket: https://www.notion.so/passcultureapp/M-J-binaire-Helmfile-207ad4e0ff98808fa82cca26f99bd159?v=1b7ad4e0ff9880e8a853000c82e3bfcb&source=copy_link
I have:

ci(deploy): bump render-push-manifests actions to use helfmfile v1 (IC-235) 
