pass-culture/pass-culture-institutional

- .github/workflows/dev_on_pull_request_sonar.yml
Ticket JIRA : https://passculture.atlassian.net/browse/PC-25491
Cette PR devrait corriger le soucis sur les CI lancées par Dependabot :
* L'action va récupérer le secret sur Secret Manager
* Pour se faire elle va devoir s'authentifier en utilisant workload identity, les infos ont été mises dans les secrets de Dependabot afin que lui aussi soit capable de jouer les actions.
> (PC-25491) fix(ci): use secret manager for sonar token

- .github/workflows/reusable_docker_build.yml
J'ai oublié que le nom d'une branche quand on fait une PR et quand on push n'est pas le même pour les github actions
> ci: fix add docker build to main workflow

- .github/workflows/on_push_or_dispatch_deploy_testing.yml
On a besoin d'avoir le workflow_dispatch pour le déploiement testing également pour pouvoir le déclencher depuis Strapi.
> ci: add workflow dispatch for testing deployment (PC-26040)

- .github/workflows/reusable_docker_build.yml
Correction du workflow de build d'image pour fonctionner même lorsque la branche contient un / ce qui est invalide pour un tag docker.
> ci: fix docker tag when a slash is in branch name

- .github/workflows/reusable_docker_build.yml
Lors du build docker dans le cadre d'une PR, le tag donné à l'image docker n'est pas le bon est correspond au commit parent entre les deux branches. Cette PR corrige cela.
> ci: fix docker image tagging on PRs

- README.md
- content_management_system/README.md
- public_website/README.md
- public_website/__tests__/pages/home.test.tsx
- public_website/__tests__/utils/fetchBackend.test.ts
- public_website/__tests__/utils/fetchCMS.test.ts
- public_website/src/utils/fetchBackend.ts
- public_website/src/utils/fetchCMS.ts
https://passculture.atlassian.net/browse/PC-27773
To test, set .env of Next to:
```
STRAPI_API_URL=https://siteinstit-cms.testing.passculture.team
BACKEND_API_URL=https://backend.testing.passculture.team/
```
Start Next and check if playlist show correctly.
> fix: removed unsued env variables from Next

- public_website/src/pages/index.tsx
@Lucasbeneston le fix pour le problème de la home qui ne buildait pas.
Étrangement, lorsqu'on filtre avec l'opérateur `$eq`, ça remonte une 403 tandis qu'avec `$eqi` (case insensitive) ça fonctionne (https://docs.strapi.io/dev-docs/api/rest/filters-locale-publication#filtering). Ça ressemble à un bug côté Strapi et je sais pas l'expliquer mais ça fonctionne.
- Avec `$eq` : https://siteinstit-cms.testing.passculture.team/api/news-list?sort[0]=date%3Adesc&populate[0]=image&pagination[limit]=3&filters[category][$eq]=%C3%89tude
- Avec `$eqi` : https://siteinstit-cms.testing.passculture.team/api/news-list?sort[0]=date%3Adesc&populate[0]=image&pagination[limit]=3&filters[category][$eqi]=%C3%89tude
> fix: use eqi instead of eq to filter latest studies on home page

- public_website/src/lib/blocks/FilterContainer.tsx
- public_website/src/pages/liste-jeune.tsx
@affo-bien-fonde ou @quentin-bien-fonde ou @adrien-bien-fonde 
Il y a des warning eslint (normalment sur le répo de l'application pass Culture ce sont des erreurs mais nous avons voulu les laisser en warning pour le temps de votre développement), est-ce que vous pouvez voir si ils sont légitimes ou non ? J'ai ignoré les warning ici pour vous montrer ou ça remonte. Je n'ai pas le temps de vérifier si oui ou non il faut modifier les deps des useEffect
| Command         | Before | After |
| yarn test:lint  |      <img width="1002" alt="Capture d’écran 2024-03-22 à 12 32 10" src="https://github.com/pass-culture/pass-culture-institutional/assets/62059034/a556efca-a788-4130-9dec-8d3d7e3bbd7d">  |  <img width="1011" …
> feat(eslint): temporary fix react-hooks/exhaustive-deps warning

- public_website/__tests__/utils/parseTitleWithMarkup.test.ts
- public_website/src/utils/parseTitleWithMarkup.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29263
Je vais faire une seconde PR pour utiliser `parseTitleWithMarkup`
Parce que je vais devoir modifier tous les textes dans Strapi au merge (je vais le faire en fin de journée pour ne pas gêner)
Utilisation : 
```
// AVANT 
<StyledHeading dangerouslySetInnerHTML={{ __html: title }} />
// APRÈS 
<StyledHeading
aria-label={parseTitleWithMarkup(new_title).accessibilityLabel}>
{parseTitleWithMarkup(new_title).textWithMarkup}
</StyledHeading>
```
Ça fonctionne bien : 
I have:
> refactor(text): add parseTitleWithMarkup

- public_website/src/lib/blocks/PushCTA.tsx
In the `home`, when clicking `Télécharger l'application` , the event `downloadApp` wasn't being sent even if it was correctly filled in Strapi. The issue was that the component being used in strapi was called CTASection, and the data from this component was being used in the Next component `PushCTA` using `CtaLink`. I added an `onClick` calling analytics and it worked.
> fix: added missing onClick for PushCTA

- public_website/src/lib/blocks/SimplePushCta.tsx
- public_website/src/ui/components/button/Button.tsx
Un outline restait affiché une fois le clique effectué en raison du focus mis sur les buttons (Button.tsx et SimplePushCta.tsx).
Cette pull request corrige donc ce focus en modifiant la pseudo classe focus en active.
La pseudo classe focus est devenu une pseudo classe active du CtaLink et StyledButton.
La correction fait référence à la demande [ici](https://www.notion.so/tous-les-boutons-de-ce-gabarit-Quand-je-clique-dessus-le-contour-apparait-au-click-mais-quand-je-r-ed64e771237d441e8f9543d13d1647fb?pvs=4).
> fix: focus boutton

- content_management_system/src/components/block/simple-text-v2.json
- content_management_system/src/components/common/simple-text-column.json
- content_management_system/types/generated/components.d.ts
- public_website/src/lib/blocks/DetailedLogos.tsx
- public_website/src/lib/blocks/DoublePushCta.tsx
- public_website/src/lib/blocks/Header.tsx
- public_website/src/lib/blocks/ImageText.tsx
- public_website/src/lib/blocks/PiledCards/PiledCards.tsx
- public_website/src/lib/blocks/PiledCards/PiledCardsCarouselSlide.tsx
- public_website/src/lib/blocks/PushCTA.tsx
- public_website/src/lib/blocks/SimplePushCta.tsx
- public_website/src/lib/blocks/Video.tsx
- public_website/src/lib/blocks/experienceVideoCarousel/experieneVideoCarouselSlide.tsx
- public_website/src/lib/blocks/logoCarousel/logoCarousel.tsx
- public_website/src/lib/blocks/logoCarousel/logoCarouselSlide.tsx
- public_website/src/lib/blocks/verticalCarousel/VerticalCarouselSlide.tsx
- public_website/src/ui/components/button/Button.tsx
Un outline restait affiché  une fois le clique effectué en raison du focus mis sur les buttons (Button.tsx et SimplePushCta.tsx). 
Cette pull request corrige donc ce focus en modifiant la pseudo classe focus en active.
La pseudo classe focus est devenu une pseudo classe active du CtaLink et StyledButton.
La correction fait référence à la demande [ici](https://www.notion.so/tous-les-boutons-de-ce-gabarit-Quand-je-clique-dessus-le-contour-apparait-au-click-mais-quand-je-r-ed64e771237d441e8f9543d13d1647fb?pvs=4).
> Fix button focus

- public_website/src/ui/components/simulator/SliderField.tsx
Avant correction:
Quand on est au point de départ du simulateur, la jauge ne doit pas être rempli en violet.
Après correction:
La jauge se remplie selon la position du curseur.
D'autre part, il pourvait y avoir un soucis d'hydratation avec le select. Un state a été ajouté pour afficher le select coté client pour corriger le soucis.
Changement de la props inluded (false à true) du composant Slider dans le composant SliderField.tsx et ajustement css pour la classe rc-slider-track.
[Ticket sur notion.](https://www.notion.so/quand-on-est-au-point-de-d-part-du-simulateur-la-jauge-ne-doit-pas-etre-rempli-en-violet-cf-maquet-8744c9e3d4f446dd99ffe12c0093706b?pvs=4)
> fix(SliderField): simulateur jauge

- public_website/src/pages/[...slug].tsx
- public_website/src/ui/components/breadcrumb/Breadcrumb.tsx
Cette pull request permet d'afficher le fil d'arianne sur toutes les pages. 
Celui n'était présent que sur certaine page.
Les fichiers concernés par les changements :  
modified:   public_website/src/pages/[...slug].tsx : ajout d'une condition au niveau du render pour afficher Breadcrumb après le header de la page
modified:   public_website/src/ui/components/breadcrumb/Breadcrumb.tsx : prise en compte de la deuxième partie de la navigation (aboutItems) et utilisation de isStringAreEquals.
Plusieurs tickets y font référence.
Exemple : [ici](https://www.notion.so/Manque-le-fil-d-ariane-cedfd357ee2947fbb2b56ca9ee06d3f2?pvs=4)
> fix: fil arianne

- public_website/src/utils/parseText.tsx
- public_website/src/utils/stripTags.ts
Cette pull request corrige des erreurs générées sur certains pages lorsque des valeurs de champs ne sont pas renseignées mais ne sont pas traitées en condition sur leur existence notamment sur les traitements de chaines de string.
> fix: fix sur parseText et stripTags

- public_website/src/pages/actualites-pass-culture.tsx
- sonar-project.properties
Cette PR permet d'ajuster correctement la marge du bloc actu dans la page actualité.
> fix: erreur de margin listems page actu

- content_management_system/src/api/footer/content-types/footer/schema.json
- content_management_system/types/generated/contentTypes.d.ts
- public_website/src/types/contentTypes.d.ts
- public_website/src/types/props.ts
- public_website/src/ui/components/footer/Footer.tsx
- public_website/src/ui/components/header/HeaderBanner.tsx
Cette PR permet de fixer l'affichage de la banner pour télécharger l'app disponible sur les stores.
3 urls sont à renseigner : 1  pour le store apple, 1 pour les store google et une url par défaut.
La redirection s'effectue selon le device.
> fix: ajout props defaultUrl

- public_website/src/lib/blocks/experienceVideoCarousel/experienceVideoCarousel.tsx
Cette PR corrige le menu dots (experienceVideoCarousel) qui restait actif en desktop. il manquait une condition sur son affichage.
> fix: pas de menu dots en desktop

- public_website/src/pages/_document.tsx
- public_website/src/pages/actualite/[slug].tsx
Cette PR règle le problème de placement du fil d'ariane sur les pages des articles.
J'en ai profité pour modifier l'attribut lang qui était par défaut en.
> fix: fil arianne mal placé

- public_website/__tests__/hooks/useLockBodyScroll.test.tsx
- public_website/src/domain/events/events.actions.ts
- public_website/src/domain/events/events.output.ts
- public_website/src/domain/news/news.actions.ts
- public_website/src/domain/news/news.output.ts
- public_website/src/domain/resources/resources.actions.ts
- public_website/src/domain/resources/resources.output.ts
- public_website/src/hooks/useLockBodyScroll.ts
- public_website/src/lib/blocks/Faq.tsx
- public_website/src/lib/blocks/verticalCarousel/VerticalCarousel.tsx
- public_website/src/pages/actualite/[slug].tsx
- public_website/src/pages/evenement/[slug].tsx
- public_website/src/pages/ressources/[slug].tsx
- public_website/src/ui/components/header/MegaMenu.tsx
- public_website/src/ui/globalstyles.tsx
Cette PR permet d'ajouter le fil d'ariane dans le simulateur (celui ne faisant pas partie des items du megamenu, le fil d'ariane était incomplet).
D'autre part, je propose d'isoler les services requêtes (à valider). 
Enfin j'en ai profité pour faire un test sur un carousel pour améliorer l'expérience user en désactivant le scroll vertical si on scrolle le carousel (= à généraliser si concluant).
> fix: ariane simulateur et isolation requetes

- LICENSE
- public_website/src/ui/components/simulator/ResultScreen.tsx
Le Lien qui se trouve sur la vue résultat dans le simulateur ne renvoie pas sur le compte mailto défini dans le back office.
La props passée à Link était ctaLink.URL ou lieu de supportLink.URL
La props a donc été corrigée (fichier concerné ResultScreen.tsx) afin de pouvoir remonter correctement le mailto renseigné sur Srapi. (mailto:support@passculture.app)
> fix: simulator support link

- content_management_system/types/generated/components.d.ts
- public_website/src/pages/_app.tsx
- public_website/src/types/props.ts
- public_website/src/ui/components/breadcrumb/Breadcrumb.tsx
- public_website/src/ui/components/breadcrumb/breadcrumb-context.ts
Certains liens présents dans la partie basse du footer n'était pas pris en compte dans le fil d'ariane.
Effectivement, dans le contexte du fil d'ariane, n'était pris en compte que les items du menu principale qui se retrouve en partie dans le footer également)
J'ai donc ajouté la partie du footer non pris en compte dans le fil d'ariane dans le contexte (BreadcrumbContext) du fil d'arianne.
J'ai ajouté une props pour plus de cohérence BreadcrumbDataProps et modifié le traintement coté Breadcrumb.tsx.
> fix: add footer links breadcrumb

- README.md
- nginx-strapi-testing-proxy/Dockerfile
- nginx-strapi-testing-proxy/README.md
- nginx-strapi-testing-proxy/launch-testing-proxy.sh
- nginx-strapi-testing-proxy/nginx.conf
- nginx-strapi-testing-proxy/transfer-from-testing.sh
- package.json
- public_website/src/lib/analytics/analyticsProvider.ts
Cette Pull Request introduit un **proxy Nginx** pour faciliter la connexion au **Strapi de l'environnement de testing**, sécurisé derrière **Google Cloud IAP**.
L'objectif principal est de :
1. Permettre aux développeurs de connecter facilement le **frontend local** au Strapi de testing sans configuration manuelle de l'accès IAP.
2. Faciliter le **transfert de données** depuis l'environnement de testing vers la base de données locale pour les phases de développement et de tests.
---
- **`nginx-strapi-testing-proxy/`** : Contient les fichiers nécessaires pour configurer et lancer le proxy ainsi que pour transférer les données.
| **Fichier**                 | **Description**                                                                 | …
> feat(proxy): add testing proxy setup for strapi testing environment

- .github/workflows/on_dispatch_deploy_cms_production.yml
- content_management_system/src/api/simulator/content-types/simulator/schema.json
- content_management_system/types/generated/components.d.ts
- content_management_system/types/generated/contentTypes.d.ts
- public_website/src/pages/simulateur.tsx
- public_website/src/types/components.d.ts
- public_website/src/types/contentTypes.d.ts
- public_website/src/ui/components/simulator/DisabledSimulator.tsx
Cette Pull Request introduit une nouvelle fonctionnalité qui permet de désactiver le simulateur dans l’application. Ce mécanisme est utile pour gérer l’activation ou la désactivation du simulateur directement via le CMS, et adapter l’affichage sur le site public en conséquence.
- **CMS / API Simulator** :
- **Schéma du simulateur** :  
Le fichier `schema.json` a été mis à jour pour inclure deux nouvelles propriétés :
- `disableSimulator` : de type `boolean`, avec une valeur par défaut à `false` et marquée comme obligatoire.
- `disableText` : de type `text` et obligatoire, permettant d’afficher un message personnalisé lorsque le simulateur est désactivé.
- **Site Public** :
- **Page du simulateur** :  
La page `simulateur.tsx` a été modifiée pour prendre en compte l’état désactivé du …
> feat(simulator): add ability to disable simulator

- .github/workflows/reusable_public_site_deploy.yml
- public_website/testing-robots.txt
Notre site de testing ne doit **pas** être indexé par les moteurs de recherche pour éviter le référencement de contenu non-prod.
- Ajoute un `robots.txt` dédié qui interdit l’accès à tous les robots lorsque l’environnement est `testing`.
- Modifie le workflow de déploiement pour copier ce fichier de test en tant que `public/robots.txt` **uniquement** lors des builds sur l’environnement `testing`.
- **Uniquement** sur l’environnement de test : le site ne sera pas indexé.  
- L’environnement de production n’est **pas** affecté.
> feat(robots): add robots to disable seo for testing

- .github/workflows/reusable_cms_deploy.yml
Utilisation du binaire pc-render-manifest pour générer les manifests depuis la CI
Validé ici : https://github.com/pass-culture/pass-culture-institutional/actions/runs/16752370686
> ci(deploy): use pc-render-manifests (IC-284)
